wb_instalacoes/fornecedores/urls.py
from django.urls import path
from ..fornecedores import views as v
from django.contrib.auth.decorators import login_required

app_name = 'fornecedores'
urlpatterns = [
    path('', login_required(v.FornecedoresList.as_view()), name='fornecedores_list'),
    path('add/', login_required(v.add_fornecedor.as_view()), name='fornecedor_add'),
    path('<int:pk>/', login_required(v.fornecedor_detail), name='fornecedor_detail'),
    path('<int:pk>/edit/', login_required(v.FornecedorUpdate.as_view()), name='fornecedor_edit'),
    path('delete/<int:pk>', login_required(v.fornecedor_delete), name='fornecedores_delete'),
]

wb_instalacoes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('wb_instalacoes.accounts.urls')),
    path('clientes/', include('wb_instalacoes.clientes.urls')),
    path('', include('wb_instalacoes.core.urls')),
    path('fornecedores/', include('wb_instalacoes.fornecedores.urls')),
    path('produto/', include('wb_instalacoes.produto.urls')),
    path('estoque/', include('wb_instalacoes.estoque.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wb_instalacoes/fornecedores/models.py
from django.db import models
from django.urls import reverse_lazy


# variaveis de lista

ESTADOS_BR = (
    ('---', '---'),
    ('Acre (AC)', 'Acre (AC)'),
    ('Alagoas (AL)', 'Alagoas (AL)'),
    ('Amapá (AP)', 'Amapá (AP)'),
    ('Amazonas (AM)', 'Amazonas (AM)'),
    ('Bahia (BA)', 'Bahia (BA)'),
    ('Ceará (CE)', 'Ceará (CE)'),
    ('Distrito Federal (DF)', 'Distrito Federal (DF)'),
    ('Espírito Santo (ES)', 'Espírito Santo (ES)'),
    ('Goiás (GO)', 'Goiás (GO)'),
    ('Maranhão (MA)', 'Maranhão (MA)'),
    ('Mato Grosso (MT)', 'Mato Grosso (MT)'),
    ('Mato Grosso do Sul (MS)', 'Mato Grosso do Sul (MS)'),
    ('Minas Gerais (MG)', 'Minas Gerais (MG)'),
    ('Pará (PA)', 'Pará (PA)'),
    ('Paraíba (PB)', 'Paraíba (PB)'),
    ('Paraná (PR)', 'Paraná (PR)'),
    ('Pernambuco (PE)', 'Pernambuco (PE)'),
    ('Piauí (PI)', 'Piauí (PI)'),
    ('Rio de Janeiro (RJ)', 'Rio de Janeiro (RJ)'),
    ('Rio Grande do Norte (RN)', 'Rio Grande do Norte (RN)'),
    ('Rio Grande do Sul (RS)', 'Rio Grande do Sul (RS)'),
    ('Rondônia (RO)', 'Rondônia (RO)'),
    ('Roraima (RR)', 'Roraima (RR)'),
    ('Santa Catarina (SC)', 'Santa Catarina (SC)'),
    ('São Paulo (SP)', 'São Paulo (SP)'),
    ('Sergipe (SE)', 'Sergipe (SE)'),
    ('Tocantins (TO)', 'Tocantins (TO)'),
)



# Create your models here.
class Fornecedor(models.Model):
    fornecedor = models.CharField('Razão Social', max_length=50, unique=True)
    cnpj = models.CharField('CNPJ', max_length=50, unique=True)
    inscricao = models.CharField('Inscrição Estadual', max_length=50, unique=True)
    telefone = models.CharField('Telefone', max_length=20)

    # dados de endereco (transformar em um campo so)
    endereco = models.CharField('Endereço completo', max_length=100, blank=True)

    class Meta:
        ordering = ('fornecedor', )

    def __str__(self):
        return self.fornecedor

    def get_absolute_url(self):
        return reverse_lazy('fornecedores:fornecedor_detail', kwargs={'pk': self.pk})

wb_instalacoes/fornecedores/forms.py
from django import forms
from .models import Fornecedor


class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = '__all__'

wb_instalacoes/fornecedores/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Fornecedor
from django.contrib import messages
from .forms import FornecedorForm
from django.views.generic import CreateView, ListView
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.
class add_fornecedor(CreateView):
    model = Fornecedor
    template_name = 'fornecedor_form.html'
    form_class = FornecedorForm


class FornecedorUpdate(CreateView):
    model = Fornecedor
    template_name = 'fornecedor_form.html'
    form_class = FornecedorForm


class FornecedoresList(ListView):
    model = Fornecedor
    template_name = 'fornecedores_list.html'
    paginate_by = 10


@login_required
def fornecedor_delete(request, pk):
    fornecedor = Fornecedor.objects.get(pk=pk)
    fornecedor.delete()
    messages.success(request, 'Fornecedor deletado com sucesso.')
    return HttpResponseRedirect(reverse('fornecedores:fornecedores_list'))


@login_required
def fornecedor_detail(request, pk):
    template_name = 'fornecedores_detail.html'
    obj = Fornecedor.objects.get(pk=pk)
    search = request.GET.get('search')
    if search:
        obj = obj.filter(fornecedor__icontains=search)
    context = {'object': obj}
    return render(request, template_name, context)

wb_instalacoes/fornecedores/templates/fornecedor_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load bootstrap %}

{% block css %}
  <style>
    .form-control {
      margin: 10px;
    }
  </style>
{% endblock css %}

{% block content %}
  {{ field }}
  <div class="row">
    <div class="col-sm-12">
      <form method="POST" novalidate>
        {% csrf_token %}
        <legend style="border-bottom: 1px solid #e5e5e5;">Adicionar Fornecedor</legend>
        <h5>Dados do cliente</h5>
        <div class="row">
          <div class="col-sm-6">
            {% for field in form.visible_fields %}
              <div class="form-group{% if field.errors %} has-error {% endif%}">
                <label for="{{ field.id_for_label }}">
                  {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                  {% else %}
                    {{ field.label }}
                  {% endif %}
                </label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                  <span class="text-muted">{{ error }}</span>
                {% endfor %}
              </div>
            {% endfor %}
            {{ formset.management_form }}
          </div>
        </div>

        <div class="row float-right">
          <div class="col-sm-12" style="margin-top: 10px;">
            <div class="form-inline buttons">
              <a href="{% url 'fornecedores:fornecedores_list' %}" class="btn btn-danger">
                <i class="fa fa-times"></i>
                Cancelar
              </a>
              <div style="padding: 10px;">
                <button class="btn btn-primary" value="Save">
                  <i class="fa fa-floppy-o"></i>
                  Salvar
                </button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

wb_instalacoes/fornecedores/templates/fornecedores_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{object}}</h1>
    <div style="padding: 10px;">
        <a href="{% url 'fornecedores:fornecedor_edit' object.pk %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil">Editar</span>
            </button>
        </a>
        <a href="{% url 'fornecedores:fornecedores_list' %}" class="btn btn-warning">Voltar</a>
        <a href="{% url 'fornecedores:fornecedores_delete' object.pk %}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>  Delete</a>
    </div>
    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Razão Social</th>
                    <td>{{object.fornecedor}}</td>
                </tr>
                <tr>
                    <th class="text-right">CNPJ</th>
                    <td>{{object.cnpj}}</td>
                </tr>
                <tr>
                    <th class="text-right">Inscrição Estadual</th>
                    <td>{{object.inscricao}}</td>
                </tr>
                <tr>
                    <th class="text-right">Telefone</th>
                    <td>{{object.telefone}}</td>
                </tr>
                <tr>
                    <th class="text-right">Endereço</th>
                    <td>{{object.endereco}}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

wb_instalacoes/fornecedores/templates/fornecedores_list.html
{% extends "base.html" %}

{% block content %}
{% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
{% endfor %}
<div class="page-header">
    <h2>Lista de Fornecedores
        <a href="{% url 'fornecedores:fornecedor_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span>Cadastrar
            </button>
        </a>
    </h2>
    {%if object_list%}
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Razão Social</td>
                <td>CNPJ</td>
                <td>Telefone</td>
                <td>Endereço</td>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{{ object.get_absolute_url }}">{{ object.fornecedor }}</a></td>
                    <td>{{object.cnpj}}</td>
                    <td>{{object.telefone}}</td>
                    <td>Rua {{object.rua}}, nª{{object.numero}}, {{object.complemento}}; {{object.bairro}}, {{object.cidade}} - {{object.estado}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p class="alert alert-warning">Sem itens na lista</p>
    {% endif %}
</div>
{% include "includes/pagination.html" %}
{% endblock content %}