wb_instalacoes/clientes/urls.py
from django.urls import path
from ..clientes import views as v
from django.contrib.auth.decorators import login_required

app_name = 'clientes'
urlpatterns = [
    path('', login_required(v.ClientesList.as_view()), name='clientes_list'),
    path('add/', login_required(v.add_client.as_view()), name='clientes_add'),
    path('<int:pk>/', login_required(v.cliente_detail), name='cliente_detail'),
    path('<int:pk>/edit/', login_required(v.ClienteUpdate.as_view()), name='cliente_edit'),
    path('delete/<int:pk>', login_required(v.cliente_delete), name='cliente_delete'),
]

wb_instalacoes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('wb_instalacoes.accounts.urls')),
    path('clientes/', include('wb_instalacoes.clientes.urls')),
    path('', include('wb_instalacoes.core.urls')),
    path('fornecedores/', include('wb_instalacoes.fornecedores.urls')),
    path('produto/', include('wb_instalacoes.produto.urls')),
    path('estoque/', include('wb_instalacoes.estoque.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wb_instalacoes/clientes/models.py
from django.db import models
from django.urls import reverse_lazy


# variaveis de lista
PESSOA_TIPO = (
    ('---', '---'),
    ('Pessoa Física', 'Pessoa Física'),
    ('Pessoa Juridica', 'Pessoa Jurídica'),
)

ESTADOS_BR = (
    ('---', '---'),
    ('Acre (AC)', 'Acre (AC)'),
    ('Alagoas (AL)', 'Alagoas (AL)'),
    ('Amapá (AP)', 'Amapá (AP)'),
    ('Amazonas (AM)', 'Amazonas (AM)'),
    ('Bahia (BA)', 'Bahia (BA)'),
    ('Ceará (CE)', 'Ceará (CE)'),
    ('Distrito Federal (DF)', 'Distrito Federal (DF)'),
    ('Espírito Santo (ES)', 'Espírito Santo (ES)'),
    ('Goiás (GO)', 'Goiás (GO)'),
    ('Maranhão (MA)', 'Maranhão (MA)'),
    ('Mato Grosso (MT)', 'Mato Grosso (MT)'),
    ('Mato Grosso do Sul (MS)', 'Mato Grosso do Sul (MS)'),
    ('Minas Gerais (MG)', 'Minas Gerais (MG)'),
    ('Pará (PA)', 'Pará (PA)'),
    ('Paraíba (PB)', 'Paraíba (PB)'),
    ('Paraná (PR)', 'Paraná (PR)'),
    ('Pernambuco (PE)', 'Pernambuco (PE)'),
    ('Piauí (PI)', 'Piauí (PI)'),
    ('Rio de Janeiro (RJ)', 'Rio de Janeiro (RJ)'),
    ('Rio Grande do Norte (RN)', 'Rio Grande do Norte (RN)'),
    ('Rio Grande do Sul (RS)', 'Rio Grande do Sul (RS)'),
    ('Rondônia (RO)', 'Rondônia (RO)'),
    ('Roraima (RR)', 'Roraima (RR)'),
    ('Santa Catarina (SC)', 'Santa Catarina (SC)'),
    ('São Paulo (SP)', 'São Paulo (SP)'),
    ('Sergipe (SE)', 'Sergipe (SE)'),
    ('Tocantins (TO)', 'Tocantins (TO)'),
)


class Cliente(models.Model):
    tipo = models.CharField(max_length=50, choices=PESSOA_TIPO, default='---')
    cliente = models.CharField('Nome / Razão Social', max_length=50, unique=True)
    cpf_cnpj = models.CharField('CPF / CNPJ', max_length=50, unique=True)
    telefone = models.CharField('Telefone', max_length=20)

    # dados de endereco
    endereco = models.CharField('Endereço completo', max_length=100, blank=False, null=True)

    class Meta:
        ordering = ('cliente', )

    def __str__(self):
        return self.cliente

    def get_absolute_url(self):
        return reverse_lazy('clientes:cliente_detail', kwargs={'pk': self.pk})

wb_instalacoes/clientes/forms.py
from django import forms
from .models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

wb_instalacoes/clientes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Cliente
from django.contrib import messages
from .forms import ClienteForm
from django.views.generic import CreateView, ListView
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.
class add_client(CreateView):
    model = Cliente
    template_name = 'cliente_form.html'
    form_class = ClienteForm


class ClienteUpdate(CreateView):
    model = Cliente
    template_name = 'cliente_form.html'
    form_class = ClienteForm


class ClientesList(ListView):
    model = Cliente
    template_name = 'clientes_list.html'
    paginate_by = 10


@login_required
def cliente_delete(request, pk):
    cliente = Cliente.objects.get(pk=pk)
    cliente.delete()
    messages.success(request, 'Cliente deletado com sucesso.')
    return HttpResponseRedirect(reverse('clientes:clientes_list'))



@login_required
def cliente_detail(request, pk):
    template_name = 'cliente_detail.html'
    obj = Cliente.objects.get(pk=pk)
    search = request.GET.get('search')
    if search:
        obj = obj.filter(cliente__icontains=search)
    context = {'object': obj}
    return render(request, template_name, context)

wb_instalacoes/clientes/templates/cliente_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{object}}</h1>
    <div style="padding: 10px;">
        <a href="{% url 'clientes:cliente_edit' object.pk %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil">Editar</span>
            </button>
        </a>
        <a href="{% url 'clientes:clientes_list' %}" class="btn btn-warning">Voltar</a>
        <a href="{% url 'clientes:cliente_delete' object.pk %}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>  Delete</a>
    </div>
    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Nome</th>
                    <td>{{object.cliente}}</td>
                </tr>
                <tr>
                    <th class="text-right">Tipo de Cliente</th>
                    <td>{{object.tipo}}</td>
                </tr>
                <tr>
                    <th class="text-right">CPF / CNPJ</th>
                    <td>{{object.cpf_cnpj}}</td>
                </tr>
                <tr>
                    <th class="text-right">Telefone</th>
                    <td>{{object.telefone}}</td>
                </tr>
                <tr>
                    <th class="text-right">Endereço</th>
                    <td>{{object.endereco}}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

wb_instalacoes/clientes/templates/cliente_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load bootstrap %}

{% block css %}
  <style>
    .form-control {
      margin: 10px;
    }
  </style>
{% endblock css %}

{% block content %}
  {{ field }}
  <div class="row">
    <div class="col-sm-12">
      <form method="POST" novalidate>
        {% csrf_token %}
        <legend style="border-bottom: 1px solid #e5e5e5;">Minha Empresa</legend>
        <h5>Dados do cliente</h5>
        <div class="row">
          <div class="col-sm-6">
            {% for field in form.visible_fields %}
              <div class="form-group{% if field.errors %} has-error {% endif%}">
                <label for="{{ field.id_for_label }}">
                  {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                  {% else %}
                    {{ field.label }}
                  {% endif %}
                </label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                  <span class="text-muted">{{ error }}</span>
                {% endfor %}
              </div>
            {% endfor %}
            {{ formset.management_form }}
          </div>
        </div>

        <div class="row float-right">
          <div class="col-sm-12" style="margin-top: 10px;">
            <div class="form-inline buttons">
              <a href="{% url 'clientes:clientes_list' %}" class="btn btn-danger">
                <i class="fa fa-times"></i>
                Cancelar
              </a>
              <div style="padding: 10px;">
                <button class="btn btn-primary" value="Save">
                  <i class="fa fa-floppy-o"></i>
                  Salvar
                </button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

wb_instalacoes/clientes/templates/clientes_list.html
{% extends "base.html" %}

{% block content %}
{% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
{% endfor %}
<div class="page-header">
    <h2>Lista de Clientes
        <a href="{% url 'clientes:clientes_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span>Cadastrar
            </button>
        </a>
    </h2>
    {%if object_list%}
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Nome</td>
                <td>Tipo de Cliente</td>
                <td>Telefone</td>
                <td>Email</td>
                <td>Endereço</td>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{{ object.get_absolute_url }}">{{ object.cliente }}</a></td>
                    <td>{{object.tipo}}</td>
                    <td>{{object.telefone}}</td>
                    <td>{{object.email}}</td>
                    <td>{{object.rua}}, nª {{object.numero}}, {{object.bairro}}, {{object.cidade}} - {{object.estado}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p class="alert alert-warning">Sem itens na lista</p>
    {% endif %}
</div>
{% include "includes/pagination.html" %}
{% endblock content %}