wb_instalacoes/produto/urls.py
from django.urls import path
from ..produto import views as v
from django.contrib.auth.decorators import login_required

app_name = 'produto'
urlpatterns = [
    path('', login_required(v.ProdutoList.as_view()), name='produto_list'),
    path('<int:pk>/', login_required(v.produto_detail), name='produto_detail'),
    path('add/', login_required(v.ProdutoCreate.as_view()), name='produto_add'),
    path('<int:pk>/edit/', login_required(v.ProdutoUpdate.as_view()), name='produto_edit'),
    path('delete/<int:pk>', login_required(v.produto_delete), name='produto_delete'),
    path('delete_all/', login_required(v.delete_all), name='delete_all'),
    path('<int:pk>/json/', login_required(v.produto_json), name='produto_json'),
    path('import/csv/', login_required(v.import_csv), name='import_csv'),
    path('export/xlsx/', login_required(v.exportar_produtos_xlsx), name='export_xlsx'),
]

wb_instalacoes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('wb_instalacoes.accounts.urls')),
    path('clientes/', include('wb_instalacoes.clientes.urls')),
    path('', include('wb_instalacoes.core.urls')),
    path('fornecedores/', include('wb_instalacoes.fornecedores.urls')),
    path('produto/', include('wb_instalacoes.produto.urls')),
    path('estoque/', include('wb_instalacoes.estoque.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wb_instalacoes/produto/models.py
from django.db import models
from django.urls import reverse_lazy
from datetime import datetime
from ..fornecedores.models import Fornecedor
from decimal import Decimal
# Create your models here.

MEDIDAS = (
    ('M- Metros', 'Metros (m)'),
    ('KG - Kilos', 'Kilos (Kg)'),
    ('UN- Unidades', 'Unidades'),
)


class Produto(models.Model):
    codigo = models.CharField('Codigo de Registro', max_length=8, unique=True)
    produto = models.CharField('Produto', max_length=100, unique=True)
    medida = models.CharField('Unidade de Medida', max_length=50, choices=MEDIDAS)
    preco_compra = models.DecimalField('Preço de compra da unidade (R$)', max_digits=7, decimal_places=2)
    lucro = models.IntegerField('Margem de lucro (%)', null=True)
    preco_venda = 0
    fabricante = models.ForeignKey(Fornecedor, on_delete=models.CASCADE, null=True)
    estoque = models.IntegerField('estoque atual', null=True)
    data = datetime.now()


    class Meta:
        ordering = ('produto', )

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }

wb_instalacoes/produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'

wb_instalacoes/produto/views.py
import csv
import io
from datetime import datetime
from django.contrib import messages
from ..produto.actions.export_xlsx import export_xlsx
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView
from .models import Produto
from .forms import ProdutoForm
# Create your views here.


@login_required
def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 10


@login_required
def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    obj.preco_venda = int(obj.preco_compra) + int(obj.preco_compra) * (int(obj.lucro)/100)
    context = {'object': obj}
    return render(request, template_name, context)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


@login_required
def produto_delete(request, pk):
    produto = Produto.objects.get(pk=pk)
    produto.delete()
    messages.success(request, 'Produto deletado com sucesso.')
    return HttpResponseRedirect(reverse('produto:produto_list'))


@login_required
def delete_all(request):
    if request.method == 'POST':
        for produto in Produto.objects.all():
            if str(produto.pk) in request.POST:  # verifica se name-input foi enviado na requisição
                if request.POST[str(produto.pk)] == 'on':
                    produto.delete()
    return HttpResponseRedirect(reverse('produto:produto_list'))




@login_required
def produto_json(request, pk):
    # retorna o produto, ID e estoque
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    aux = []
    for item in data:
        codigo = item.get('codigo')
        produto = item.get('produto')
        medida = item.get('medida')
        preco = item.get('preco')
        estoque = item.get('quantidade')
        obj = Produto(
            codigo=codigo,
            produto=produto,
            medida=medida,
            preco=preco,
            estoque=estoque,
        )
        aux.append(obj)
    print(aux)
    Produto.objects.bulk_create(aux)


@login_required
def import_csv(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        # Lendo arquivo InMemoryUploadedFile
        file = myfile.read().decode('utf-8')
        reader = csv.DictReader(io.StringIO(file))
        # Gerando uma list comprehension
        data = [line for line in reader]
        save_data(data)
        return HttpResponseRedirect(reverse('produto:produto_list'))

    template_name = 'produto_import.html'
    return render(request, template_name)


@login_required
def exportar_produtos_xlsx(request):
    MDATA = datetime.now().strftime('%Y-%m-%d')
    model = 'Produto'
    filename = 'produtos_exportados.xlsx'
    _filename = filename.split('.')
    filename_final = f'{_filename[0]}_{MDATA}.{_filename[1]}'
    queryset = Produto.objects.all().values_list(
        'codigo',
        'produto',
        'preco',
        'fabricante',
        'estoque',
    )
    columns = ('Codigo', 'Produto', 'Preço', 'Fabricante', 'Estoque')
    response = export_xlsx(model, filename_final, queryset, columns)
    return response

wb_instalacoes/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{object}}</h1>
    <div style="padding: 10px;">
        <a href="{% url 'produto:produto_edit' object.pk %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil">Editar</span>
            </button>
        </a>
        <a href="{% url 'produto:produto_list' %}" class="btn btn-warning">Voltar</a>
        <a href="{% url 'produto:produto_delete' object.pk %}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>  Deletar</a>
    </div>

    <div class="col-sm-6">
        <table class="table table-user-information">
            <tbody>
                <tr>
                    <th class="text-right">Codigo de registro</th>
                    <td>
                        {{object.codigo}}
                    </td>
                </tr>
                <tr>
                    <th class="text-right">Preço de compra(R$)</th>
                    <td> {{object.preco_compra}}</td>
                </tr>
                <tr>
                    <th class="text-right">Preço de venda(R$)</th>
                    <td> {{object.preco_venda}} </td>
                </tr>
                <tr>
                    <th class="text-right">Margem de lucro (%)</th>
                    <td> {{object.lucro}} </td>
                </tr>
                <tr>
                    <th class="text-right">Fornecedor</th>
                    <td>{{object.fabricante}}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

wb_instalacoes/produto/templates/produto_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

  <form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif%}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-inline buttons">
      <a href="{% url 'produto:produto_list' %}" class="btn btn-danger">
        <i class="fa fa-times"></i>
        Cancelar
      </a>
      <div style="padding: 10px;">
        <button type="submit" class="btn btn-success">Cadastrar</button>
      </div>
    </div>
  </form>

{% endblock content %}

{% block js %}

  <script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

wb_instalacoes/produto/templates/produto_import.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
      <form method="POST" enctype="multipart/form-data">
          <h5>Campos do produto:</h5>
        {% csrf_token %}
        <input name="myfile" type="file" />
          <div class="form-inline buttons">
              <div style="padding: 10px;">
                <button type="submit" class="btn btn-success">Upload</button>
              </div>
              <a href="{% url 'produto:produto_list' %}" class="btn btn-danger">
                <i class="fa fa-times"></i>
                Cancelar
              </a>
          </div>
      </form>
{% endblock content %}

wb_instalacoes/produto/templates/produto_list.html
{% extends "base.html" %}



{% block content %}
{% for message in messages %}
    {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
    {% endif %}
{% endfor %}


<form action="{% url 'produto:delete_all' %}" method="post">
    {% csrf_token %}
    <div class="page-header">
        <h2>Lista de Produtos</h2>

        <div class="col-sm-12" style="margin-top: 10px;">
            <div class="form-inline buttons">
              <div style="padding: 10px;">
                <a href="{% url 'produto:produto_add' %}">
                    <button type="button" class="btn btn-primary">
                      <span class="fa fa-plus"></span> Adicionar
                    </button>
                </a>
              </div>
                <a href="{% url 'produto:export_xlsx' %}">
                    <div style="padding: 10px;">
                        <button style="background-image: linear-gradient(#b53438,  #561819);" type="submit" class="btn btn-success">Exportar Produtos</button>
                    </div>
                </a>
                <input type="submit" class="btn  btn-light" value="Apagar"></input>
            </div>
        </div>

        {%if object_list%}
        <table class="table table-striped">
            <thead>
                <tr>
                    <td></td>
                    <td class="text-center">Codigo</td>
                    <td class="text-center">Produto</td>
                    <td class="text-center">Preço</td>
                    <td class="text-center">Unidade de Medida</td>
                    <td class="text-center">Fabricante</td>
                    <td class="text-center">Quantidade</td>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td><input value=True type="checkbox" id={{object.pk}} name={{object.pk}}></td>
                        <td class="text-center">{{object.codigo}}</td>
                        <td class="text-center">
                            <a  href="{{object.get_absolute_url}}">{{object.produto}}</a>
                        </td>
                        <td class="text-center">R$ <span >{{object.preco}}</span></td>
                        <td class="text-center"> <span >{{object.medida}}</span></td>
                        <td class="text-center">{{object.fabricante}}</td>
                        <td class="text-center">{{object.estoque}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p class="alert alert-warning">Sem itens na lista</p>
        {% endif %}
    </div>
</form>
{% include "includes/pagination.html" %}
{% block js %}

{% endblock js %}
{% endblock content %}