wb_instalacoes/accounts/urls.py
from django.urls import path
from ..accounts import views as v

app_name = 'accounts'
urlpatterns = [
    path('login/', v.user_login, name='user_login'),
    path('new_user/', v.CreateUser.as_view(), name='new_user'),
]

wb_instalacoes/clientes/urls.py
from django.urls import path
from ..clientes import views as v
from django.contrib.auth.decorators import login_required

app_name = 'clientes'
urlpatterns = [
    path('', login_required(v.ClientesList.as_view()), name='clientes_list'),
    path('add/', login_required(v.add_client.as_view()), name='clientes_add'),
    path('<int:pk>/', login_required(v.cliente_detail), name='cliente_detail'),
    path('<int:pk>/edit/', login_required(v.ClienteUpdate.as_view()), name='cliente_edit'),
    path('delete/<int:pk>', login_required(v.cliente_delete), name='cliente_delete'),
]

wb_instalacoes/core/urls.py
from django.urls import path

from ..core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

wb_instalacoes/estoque/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from ..estoque import views as v

app_name = 'estoque'


entrada_patterns = [
    path('', login_required(v.EstoqueEntradaList.as_view()), name='estoque_entrada_list'),
    path('add/', login_required(v.estoque_entrada_add), name='estoque_entrada_add'),
]

saida_patterns = [
    path('', login_required(v.EstoqueSaidaList.as_view()), name='estoque_saida_list'),
    path('add/', login_required(v.estoque_saida_add), name='estoque_saida_add'),
]


urlpatterns = [
    path('<int:pk>/', login_required(v.EstoqueDetail.as_view()), name='estoque_detail'),
    path('<int:pk>/geraPDF/', login_required(v.pdf_generate), name='gerarPDF'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
]

wb_instalacoes/produto/urls.py
from django.urls import path
from ..produto import views as v
from django.contrib.auth.decorators import login_required

app_name = 'produto'
urlpatterns = [
    path('', login_required(v.ProdutoList.as_view()), name='produto_list'),
    path('<int:pk>/', login_required(v.produto_detail), name='produto_detail'),
    path('add/', login_required(v.ProdutoCreate.as_view()), name='produto_add'),
    path('<int:pk>/edit/', login_required(v.ProdutoUpdate.as_view()), name='produto_edit'),
    path('delete/<int:pk>', login_required(v.produto_delete), name='produto_delete'),
    path('delete_all/', login_required(v.delete_all), name='delete_all'),
    path('<int:pk>/json/', login_required(v.produto_json), name='produto_json'),
    path('import/csv/', login_required(v.import_csv), name='import_csv'),
    path('export/xlsx/', login_required(v.exportar_produtos_xlsx), name='export_xlsx'),
]

wb_instalacoes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('wb_instalacoes.accounts.urls')),
    path('clientes/', include('wb_instalacoes.clientes.urls')),
    path('', include('wb_instalacoes.core.urls')),
    path('fornecedores/', include('wb_instalacoes.fornecedores.urls')),
    path('produto/', include('wb_instalacoes.produto.urls')),
    path('estoque/', include('wb_instalacoes.estoque.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wb_instalacoes/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

wb_instalacoes/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'index.html')

wb_instalacoes/core/templates/includes/nav.html
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" style="background-color: black;">
  <a class="navbar-brand" href="{% url 'core:index' %}"><img src="{% static 'imgs/logo/wb.png' %}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" style="color: white;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'produto:produto_list' %}" >Produtos</a>
          <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entradas</a>
          <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Saidas</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" style="color: white;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Gerenciar</a>
        <div class="dropdown-menu" aria-labelledby="dropdown03">
          <a class="dropdown-item" href="{% url 'clientes:clientes_list' %}" >Clientes</a>
          <a class="dropdown-item" href="{% url 'fornecedores:fornecedores_list' %}">Fornecedores</a>
        </div>
      </li>
    </ul>
    {% if user.is_authenticated %}
      <ul class="navbar-nav px-3">
          <a style="color: white; margin-left: 20px;" href="{% url 'accounts:user_login' %}">Sair</a>
      </ul>
    {% endif %}
  </div>
</nav>

wb_instalacoes/core/templates/includes/pagination.html
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      <!--Laço que roda todas as paginas -->
      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}

          {% if page_obj.number == pg %}
            <li class="page-item"><a class="page-link" style="background-color: #575251; color: white;" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% endif %}

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}

        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>